export const TOGGLE_FAV = "TOGGLE_FAV";

export const UPDATE_DEVICE_VALUE_TO_STORE = "UPDATE_DEVICE_VALUE_TO_STORE";

export const ADD_DEVICE = "ADD_DEVICE";

export const REMOVE_DEVICE = "REMOVE_DEVICE";

export const FETCH_DATA = "FETCH_DATA";
